CREATE TABLE TB_PROFESSOR(
	ID_PROFESSOR SMALLINT PRIMARY KEY,
	NOME_PROF VARCHAR(50),
	SOBRENOME_PROF VARCHAR(75)
)

CREATE TABLE TB_CATEGORIA(
	ID_CATEGORIA SMALLINT PRIMARY KEY IDENTITY,
	CATEGORIA VARCHAR(60) NOT NULL
)

ALTER TABLE TB_CURSOS
DROP COLUMN ID_PROFESSOR

ALTER TABLE TB_CURSOS ADD ID_PROFESSOR SMALLINT NOT NULL
CONSTRAINT FK_ID_PROFESSOR FOREIGN KEY(ID_PROFESSOR) REFERENCES TB_PROFESSOR


ALTER TABLE TB_CURSOS ADD ID_CATEGORIA SMALLINT NOT NULL
CONSTRAINT FK_ID_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES TB_CATEGORIA


