CREATE INDEX INDICE_NOME_CURSO ON TB_CURSOS(NOME_CURSO)


--CRIAR REGRAS, PREÇOS NÃO PODEM SER MENORES DO QUE 15.00
CREATE RULE RP_PRECO AS @VALOR > 15.00

EXECUTE sp_bindrule RP_PRECO, 'TB_CURSOS.PRECO_CURSO'

SELECT * FROM TB_CURSOS


UPDATE TB_CURSOS SET PRECO_CURSO = 85 WHERE ID_CURSO = 103
UPDATE TB_CURSOS SET PRECO_CURSO = 10 WHERE ID_CURSO = 103