CREATE TABLE TB_CURSOS(
	ID_CURSO SMALLINT PRIMARY KEY IDENTITY(100,1),
	NOME_LIVRO VARCHAR(50) NOT NULL,
	ID_PROFESSOR SMALLINT NOT NULL,
	DATA_CRIACAO DATETIME NOT NULL,
	PRECO_CURSO MONEY NOT NULL
)