INSERT INTO TB_PROFESSOR(ID_PROFESSOR,NOME_PROF,SOBRENOME_PROF)
VALUES(1,'JOÃO','MARIA')

INSERT INTO TB_PROFESSOR(ID_PROFESSOR,NOME_PROF,SOBRENOME_PROF)
VALUES(2,'FABIO','VASCONCELO')

INSERT INTO TB_PROFESSOR(ID_PROFESSOR,NOME_PROF,SOBRENOME_PROF)
VALUES(3,'PAULA','FREITAS')

INSERT INTO TB_PROFESSOR(ID_PROFESSOR,NOME_PROF,SOBRENOME_PROF)
VALUES(4,'DANIELA','FREITAS')

INSERT INTO TB_CATEGORIA(CATEGORIA)
VALUES('WEB DESIGN')

INSERT INTO TB_CATEGORIA(CATEGORIA)
VALUES('PROGRAMAÇÃO WEB')

INSERT INTO TB_CATEGORIA(CATEGORIA)
VALUES('BANCO DE DADOS')

INSERT INTO TB_CATEGORIA(CATEGORIA)
VALUES('PROGRAMAÇÃO DESKTOP')


INSERT INTO TB_CURSOS(NOME_CURSO, DATA_CRIACAO, PRECO_CURSO, ID_PROFESSOR, ID_CURSO)
VALUES('C#','20161330',65.00,1,4)