CREATE TABLE TB_ALUNOS(
	CODALUNO SMALLINT,
	NOMEALUNO VARCHAR(20),
	NOTA1 SMALLINT,
	NOTA2 SMALLINT,
	NOTA3 SMALLINT,
	NOTA4 SMALLINT
)

INSERT INTO TB_ALUNOS VALUES (1,'HUGO',7,8,9,8)
INSERT INTO TB_ALUNOS VALUES (2,'PEDRO',8,8,8,8)
INSERT INTO TB_ALUNOS VALUES (3,'PAULA',4,2,2,3)
INSERT INTO TB_ALUNOS VALUES (4,'FABIO',9,8,5,6)

SELECT * FROM TB_ALUNOS

--CRIANDO UMA FUNÇÃO
GO
CREATE FUNCTION NOTA_MEDIA(@NOME VARCHAR(30)) 

RETURNS REAL 

AS

BEGIN

	DECLARE @MEDIA REAL 
	SELECT @MEDIA = ((NOTA1 + NOTA2 + NOTA3 + NOTA4) * 2) / 5
	FROM TB_ALUNOS
	WHERE NOMEALUNO = @NOME

	RETURN @MEDIA

END

--CHAMANDO UMA FUNÇÃO
SELECT DBO.NOTA_MEDIA('HUGO')






