--CRIANDO FUNÇÃO QUE BUSCA DADOS DE TABELAS DISTINTAS
CREATE FUNCTION MULTI_TABELA() 

RETURNS @VALORES 

TABLE(NOME_CURSO VARCHAR(50), DATA_CRIACAO DATETIME, CATEGORIA VARCHAR(50), PRECO_CURSO MONEY)

AS

BEGIN
	
	INSERT @VALORES(NOME_CURSO, DATA_CRIACAO, CATEGORIA, PRECO_CURSO)
	SELECT C.NOME_CURSO, C.DATA_CRIACAO, T.CATEGORIA, C.PRECO_CURSO
	FROM TB_CURSOS C
	INNER JOIN TB_CATEGORIA T
	ON C.ID_CATEGORIA = T.ID_CATEGORIA

	RETURN
	
END

--CHAMANDO A FUNÇÃO
SELECT * FROM MULTI_TABELA()