CREATE TABLE PRODUTOS (
	CODPRODUTO SMALLINT, 
	NOMEPRODUTO VARCHAR(20),
	PRECO MONEY, 
	QUANT SMALLINT, 
	TOTAL AS (PRECO * QUANT)
)


INSERT INTO PRODUTOS VALUES (1,'ARROZ',15.00,2)
INSERT INTO PRODUTOS VALUES (2,'FEIJÃO',10.00,4)
INSERT INTO PRODUTOS VALUES (3,'CAFÉ',12.00,5)
INSERT INTO PRODUTOS VALUES (4,'MACARRÃO',5.00,3)


SELECT * FROM PRODUTOS