--CRIANDO UMA FUNÇÃO QUE RETORNA UMA TABELA
CREATE FUNCTION RETORNAR_DADOS(@VALOR REAL)
RETURNS TABLE 
AS
	RETURN (
		SELECT C.NOME_CURSO, P.NOME_PROF, T.CATEGORIA
		FROM TB_CURSOS C 
		INNER JOIN TB_PROFESSOR P 
		ON C.ID_PROFESSOR = P.ID_PROFESSOR
		INNER JOIN TB_CATEGORIA T 
		ON C.ID_CATEGORIA = T.ID_CATEGORIA
		WHERE C.PRECO_CURSO > @VALOR
	)


--CHAMANDO A FUNÇÃO QUE RETORNA UMA TABELA
SELECT NOME_CURSO, NOME_PROF, CATEGORIA FROM RETORNAR_DADOS(60.00)