CREATE TRIGGER  trg_INSERCAO_MUDANCA_PROF_AFT_UPD 

ON TB_PROFESSOR

AFTER INSERT, UPDATE

AS

IF UPDATE(NOME_PROF) BEGIN
	PRINT 'O NOME DO PROFESSOR FOI ALTERADO'
END
ELSE BEGIN
	PRINT 'O NOME DO PROFESSOR NÃO FOI ALTERADO'
END


UPDATE TB_PROFESSOR SET NOME_PROF = 'FELIPE' WHERE ID_PROFESSOR = 1