INSERT INTO TB_PROFESSOR(ID_PROFESSOR,NOME_PROF,SOBRENOME_PROF)
VALUES(1,'JOÃO','MARIA')

INSERT INTO TB_PROFESSOR(ID_PROFESSOR,NOME_PROF,SOBRENOME_PROF)
VALUES(2,'FABIO','VASCONCELO')

INSERT INTO TB_PROFESSOR(ID_PROFESSOR,NOME_PROF,SOBRENOME_PROF)
VALUES(3,'PAULA','FREITAS')

INSERT INTO TB_PROFESSOR(ID_PROFESSOR,NOME_PROF,SOBRENOME_PROF)
VALUES(4,'DANIELA','FREITAS')

INSERT INTO TB_CATEGORIA(CATEGORIA)
VALUES('WEB DESIGN')

INSERT INTO TB_CATEGORIA(CATEGORIA)
VALUES('PROGRAMAÇÃO WEB')

INSERT INTO TB_CATEGORIA(CATEGORIA)
VALUES('BANCO DE DADOS')

INSERT INTO TB_CATEGORIA(CATEGORIA)
VALUES('PROGRAMAÇÃO DESKTOP')


INSERT INTO TB_CURSOS(NOME_CURSO, DATA_CRIACAO, PRECO_CURSO, ID_PROFESSOR, ID_CATEGORIA)
VALUES('C#','20161230',65.00,1,4)

INSERT INTO TB_CURSOS(NOME_CURSO, DATA_CRIACAO, PRECO_CURSO, ID_PROFESSOR, ID_CATEGORIA)
VALUES('JAVA WEB','20161230',65.00,2,3)

INSERT INTO TB_CURSOS(NOME_CURSO, DATA_CRIACAO, PRECO_CURSO, ID_PROFESSOR, ID_CATEGORIA)
VALUES('PHP','20161230',65.00,2,3)

INSERT INTO TB_CURSOS(NOME_CURSO, DATA_CRIACAO, PRECO_CURSO, ID_PROFESSOR, ID_CATEGORIA)
VALUES('PHOTOSHOP','20161230',65.00,3,1)