SELECT 'O PREÇO DO CURSO ' + NOME_CURSO + ' É DE R$ ' + CAST(PRECO_CURSO AS VARCHAR(6))
FROM TB_CURSOS
WHERE ID_PROFESSOR = 2

SELECT 'A DATA DE LANÇAMENTO ' + CONVERT(VARCHAR(20), DATA_CRIACAO,103)
FROM TB_CURSOS
WHERE ID_CURSO = 102