-- RETORNA O DIA, MÊS E ANO
SELECT DATENAME(DAY,GETDATE()), DATENAME(MONTH,GETDATE()), DATENAME(YEAR,GETDATE())
SELECT DATEPART(DAY,GETDATE()), DATEPART(MONTH,GETDATE()), DATEPART(YEAR,GETDATE())
SELECT DAY(GETDATE()), MONTH(GETDATE()), YEAR(GETDATE())

SELECT DATETIMEFROMPARTS(2017,11,30,3,45,59,1) HORA
