--PARTE 1 CONCEDE-GRAND
--CRIA UM LOGIN E DÁ PERMISSÕES NO BANCO

EXEC MASTER.DBO.SP_ADDLOGIN 'USRTESTE','SENHATESTE'

EXEC SP_GRANTDBACCESS 'USRTESTE','SENHATESTE'

EXEC SP_REVOKEDBACCESS 'USRTESTE'

--CONCEDENDO ACESSO DE ATUALIZAÇÃO PARA USRTESTE
GRANT UPDATE ON FUNCIONARIOS TO USRTESTE

--CONCEDENDO ACESSO DE INSERT PARA USRTESTE
GRANT INSERT ON FUNCIONARIOS TO USRTESTE

--CONCEDENDO ACESSO DE LEITURA PARA USRTESTE
GRANT SELECT ON FUNCIONARIOS TO USRTESTE

--CONCEDENDO ACESSO DE DELETE PARA USRTESTE
GRANT DELETE ON FUNCIONARIOS TO USRTESTE

--CRIANDO PROCEDURE
CREATE PROCEDURE TESTEPROC
AS
SELECT * FROM CIDADES

--EXECUTANDO PROCEDURE
EXEC TESTEPROC


--CONCEDENDO ACESSO PARA EXECUTAR PROC TESTE_PROC PARA USRTESTE
GRANT EXECUTE ON TESTEPROC TO USRTESTE

--VERIFICANDO USUARIO LOGADO
SELECT CURRENT_USER

--ALTERANDO USUARIO LOGADO
SETUSER 'USRTESTE'

--VERIFICANDO USUARIO LOGADO
SELECT CURRENT_USER


















