--ADICIONANDO 90 DIAS
SELECT GETDATE() AGORA,
	   DATEADD(DAY,90,GETDATE())

--ADICIONANDO 2 MESES
SELECT GETDATE() AGORA,
	   DATEADD(MONTH,2,GETDATE())

--ADICIONANDO 3 ANOS
SELECT GETDATE() AGORA,
	   DATEADD(YEAR,3,GETDATE())