--TESTANDO SELECT
SELECT * FROM FUNCIONARIOS

--TESTANDO INSERT
INSERT INTO FUNCIONARIOS VALUES ('MARIA','1000','TI')

--TESTANDO UPDATE
UPDATE FUNCIONARIOS SET NOME = 'MARISA' WHERE ID = '7'

--TESTANDO DELETE
DELETE FUNCIONARIOS WHERE ID = '7'

--PARTE 2 REVOGA-REVOKE

--REVOGANDO ACESSO DE ATULIACAO USRTESTE
REVOKE UPDATE ON FUNCIONARIOS TO USRTESTE

--REVOGANDO ACESSO DE INSERT USRTESTE
REVOKE INSERT ON FUNCIONARIOS TO USRTESTE

--REVOGANDO ACESSO DE LEITURA USRTESTE
REVOKE SELECT ON FUNCIONARIOS TO USRTESTE

--REVOGANDO DIREITO DE EXECUCAO DA PROC TESTE_PROC PARA USRTESTE
REVOKE EXECUTE ON TESTEPROC TO USRTESTE


--3 PARTE NEGA-DENY
--NEGANDO ACESSO DE ATUALIZACAO USRTESTE
DENY UPDATE ON FUNCIONARIOS TO USRTESTE

--NEGANDO ACESSO DE ATUALIZACAO USRTESTE
DENY INSERT ON FUNCIONARIOS TO USRTESTE

--NEGANDO ACESSO DE LEITURA USRTESTE
DENY SELECT ON FUNCIONARIOS TO USRTESTE

--NEGA ACESSO A EXECUSSÃO DE PROCEDURE
DENY EXECUTE ON TESTEPROC TO USRTESTE

