--SÓ NA MESMA SEÇÃO (CONEXÃO)
CREATE TABLE #TABELA01(
	ID VARCHAR(10) NULL,
	NOME VARCHAR(200) NULL
)

INSERT INTO #TABELA01 (ID, NOME) VALUES ('1','JOÃO')

SELECT * FROM #TABELA01



--VALE PARA MUITAS CONEXÕES
CREATE TABLE ##TABELA02(
	ID VARCHAR(10) NULL,
	NOME VARCHAR(200) NULL
)

INSERT INTO ##TABELA02 (ID, NOME) VALUES ('1','JOÃO')

SELECT * FROM ##TABELA02
