--CRIANDO TABELA TEMPORARIA
CREATE TABLE #MINHATEMPORARIA(
	CAMPO1 VARCHAR(80) NOT NULL,
	CAMPO2 MONEY NOT NULL
)

--INSERINDO DADOS NA TABELA TEMPORARIA
INSERT INTO #MINHATEMPORARIA VALUES ('REAL',1000)
INSERT INTO #MINHATEMPORARIA VALUES ('DOLAR',3000)

--SELECIONANDO DADOS NA TABELA TEMPORARIA
SELECT * FROM #MINHATEMPORARIA

--CRIANDO TABELA TEMPORARIA ATRAVÉS DE UM SELECT
SELECT * INTO #MINHATEMPORARIA2 FROM #MINHATEMPORARIA

--SELECIONANDO DADOS NA TABELA TEMPORARIA
SELECT * FROM #MINHATEMPORARIA2

--ATUALIZANDO TABELA TEMPORARIA
UPDATE #MINHATEMPORARIA SET CAMPO1 = 'LIBRA' WHERE CAMPO1 = 'REAL'

--DELETANDO REGISTROS
DELETE #MINHATEMPORARIA

--DROPANDO A TABELA TEMPORARIA
DROP TABLE #MINHATEMPORARIA
DROP TABLE #MINHATEMPORARIA2

--CRIANDO TABELA TEMPORARIO COM SELECT
SELECT NOME_MUN INTO #CIDADETEMP FROM cidades

--VERIFICANDO DADOS
SELECT * FROM #CIDADETEMP



















