CREATE TABLE CADASTRO(
	NOME VARCHAR(50) NOT NULL,
	DOCTO VARCHAR(20) NOT NULL
)

--INICIA UMA TRANSACAO
BEGIN TRANSACTION

INSERT INTO CADASTRO VALUES('ANDRE','12341244')
INSERT INTO CADASTRO VALUES('ANDRE','12341248')
INSERT INTO CADASTRO VALUES('ANDRE','12341246')

SELECT * FROM CADASTRO

--VOLTA PARA O ESTADO ANTERIOR DO BEGIN TRANSACTION
ROLLBACK

--EFETIVA AS INFORMACOES NA TABELA CADASTRO
COMMIT TRANSACTION

--OUTRO EXEMPLO

BEGIN TRANSACTION

INSERT INTO CADASTRO VALUES ('ANDRE','1231425')

--CRIA UM PONTO DE RECUPERACAO
SAVE TRANSACTION A1

INSERT INTO CADASTRO VALUES ('JOAO','1231421')

SAVE TRANSACTION A2


INSERT INTO CADASTRO VALUES ('PEDRO','1231415')

SAVE TRANSACTION A3

--RESTAURA A TABELA ATE O PONTO A2
ROLLBACK TRANSACTION A2


ROLLBACK


COMMIT TRANSACTION